<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.beviat</groupId>
        <artifactId>beviat</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>beviat-product</artifactId>
    <name>beviat-product</name>
    <description>商品核心：CRUD、分类管理、搜索、推荐</description>
    <dependencies>
        <dependency>
            <groupId>com.beviat</groupId>
            <artifactId>beviat-common</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.beviat</groupId>
            <artifactId>beviat-system</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
